### ISSUE TITLE
Installation fails on node 9.*, 10.*, 11.*

### ISSUE THREAD

**Issue by polyclick** [mbientlab/MetaWear-SDK-JavaScript#11]
I had to install nvm and go back to node version v8.15.0 for the metawear sdk to install.
It would be great if the package could be upgraded to at least the latest stable version of node: 10.15.0 (at the time of writing).

**Comment by scaryghost** [comment]
What specifically is broke when building on newer NodeJS releases?

**Comment by polyclick** [comment]
Sorry, needed some time to test this.

Example with node `10.15.0`:

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/polyclick/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/polyclick/.nvm/versions/node/v10.15.0/bin/node" "/Users/polyclick/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/polyclick/Desktop/metatest/node_modules/metawear/node_modules/ffi
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN metatest@1.0.0 No description
npm WARN metatest@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for bluetooth-hci-socket@0.5.1: wanted {"os":"linux,android,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
```

**Comment by polyclick** [comment]
When running this install in node `8.15.0`. The setup completes perfectly but I also see this is the logs:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for bluetooth-hci-socket@0.5.1: wanted {"os":"linux,android,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
```

If it really is optional, maybe it can be skipped for other node versions (no idea if this is possible)?

**Comment by scaryghost** [comment]
Does ``node-gyp`` install correctly on the newer NodeJS releases?  Based on your log, that is the module that is failing.

The ``bluetooth-hci-socket`` module is already skipped, as indicated in the log.

**Comment by polyclick** [comment]
I'm not sure how to test this tbh. These are the errors node-gyp gives:

```
                                       ^
../src/ffi.cc:111:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>("RTLD_NEXT").ToLocalChecked(), WrapPointer((char *)RTLD_NEXT), static_cast<P...
  ~~~~~~  ^
../src/ffi.cc:114:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>("RTLD_DEFAULT").ToLocalChecked(), WrapPointer((char *)RTLD_DEFAULT), static_...
  ~~~~~~  ^
../src/ffi.cc:117:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>("RTLD_SELF").ToLocalChecked(), WrapPointer((char *)RTLD_SELF), static_cast<P...
  ~~~~~~  ^
../src/ffi.cc:120:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>("RTLD_MAIN_ONLY").ToLocalChecked(), WrapPointer((char *)RTLD_MAIN_ONLY), sta...
  ~~~~~~  ^
../src/ffi.cc:123:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>("FFI_ARG_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_arg)...
  ~~~~~~  ^
../src/ffi.cc:124:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>("FFI_SARG_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_sar...
  ~~~~~~  ^
../src/ffi.cc:125:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>("FFI_TYPE_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_typ...
  ~~~~~~  ^
../src/ffi.cc:126:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>("FFI_CIF_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_cif)...
  ~~~~~~  ^
```

Which then let me to this post: https://github.com/node-ffi/node-ffi/issues/468
So bascially we're stuck with node 8?

**Comment by scaryghost** [comment]
There's nothing we can do then if node-gyp doesn't work past node8.

**Comment by andrewfmbs** [comment]
Any updates here? Just bought a sensor that I want to starting developing for.

**Comment by scaryghost** [comment]
> @scaryghost What is the reason in using `git://github.com/king6cong/node-ffi.git#ce274be` as dependency instead of using the official repo (https://github.com/node-ffi/node-ffi/commits/master) which seems to have fixed the node-gyp problems mentioned above?

The linked PR is still open.  If a fix has been in fact merged, which commit was it?

The node-ffi fork fixes an issue with callback functions being garbage collected.

**Comment by alisomay** [comment]
Node 13.0.8
Unfortunately doesn't build.
It works fine with Node 8.15.0.
Any updates on this ?

**Comment by lkasso** [comment]
Hey, unfortunately there's still no official support on node>8 for ffi and bluetooth-hci-socket which are metawear dependencies. We are a bit stuck waiting for those third parties to update.

I got it to run just fine on node v10 by doing a combination of the posts mentioned above and using a fork of the bluetooth-hci-socket that supports node v10:

1.  You can install the nodev10 compliant version of bluetooth-hci-socket using:
npm install "https://github.com/abandonware/node-bluetooth-hci-socket"
OR
npm install "https://github.com/jrobeson/node-bluetooth-hci-socket/#fix-builds-for-node-10"

2. You need to update the node-ffi library to use the latest official release 2.3.0 (I might update that in our official package.json file shortly)
npm install "https://github.com/node-ffi/node-ffi/commit/6221b31"

Again we are a bit stuck here until those two libraries/packages are officially updated to work on node v10 or above.

My version: v10.19.0
I attached my package.json file for reference.

I will keep this discussion open for now.
[package.json.txt](https://github.com/mbientlab/MetaWear-SDK-JavaScript/files/4602413/package.json.txt)

**Comment by lkasso** [comment]
Latest commit works on Node 10.
Might try Node 12 but 8 and 10 are supported and stable for now.
